#!/usr/bin/env bash
cd "$(dirname "$0")" || exit
echo "Bootstrap installs all dependencies."

echo "Installing features from git@github.com:casper-sdks/terminus-test-resources.git"

if [ -d "../terminus-test-resources/features" ]
then
    echo "terminus-test-resources exists fetching submodules."
    git submodule update --init --recursive
    git submodule update --remote
else
    echo "Cloning terminus-test-resources.git as submodule."
    git submodule add -f git@github.com:casper-sdks/terminus-test-resources.git ../terminus-test-resources
fi

if [ -d "../test/features" ]
then
  rm ../tests/features
  rm ../tests/contracts
  rm ../tests/json
fi

echo "Creating features symbolic link required for IntelliJ debugging of features"
ln -s "$(realpath "../terminus-test-resources/features")" ../tests/features
ln -s "$(realpath "../terminus-test-resources/contracts")" ../tests/contracts
ln -s "$(realpath "../terminus-test-resources/json")" ../tests/json
