# This workflow will:
#   - download and start a NCTL docker image
#   - download and install Go
#   - checkout the source code
#   - run the cucumber tests
#   - publish the xml test reports to the actions page


name: CSPR Go SDK Standard Tests
on:
  workflow_dispatch:

permissions:
  checks: write

jobs:
  build:
    name: Go SDK Standard Tests
    runs-on: ubuntu-latest
    services:
      nctl:
        image: stormeye2000/cspr-nctl:1.5
        options: --name cspr-nctl
        env:
          PREDEFINED_ACCOUNTS: 'true'
          MINIMUM_ROUND_EXPONENT: '12'
          MAXIMUM_ROUND_EXPONENT: '14'
          DEPLOY_DELAY: '30sec'
        ports:
          - 11101:11101
          - 14101:14101
          - 18101:18101
          - 25101:25101
    steps:
      # Start the NCTL docker image
      - name: Starting the NCTL docker image
        run: |
          echo "Wait for NCTL"
          sleep 30s

      # Checkout the source code
      - uses: actions/checkout@v3

      # Setup Go
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      # Run tests using gotestsum which will produce a junit file
      - name: Test
        run: |          
          go install gotest.tools/gotestsum@latest
          mkdir reports
          gotestsum --format standard-verbose --junitfile reports/report.xml

      # Publish the junit file to the action as a report
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: success() || failure()
        with:
          report_paths: 'reports/*.xml'
          detailed_summary: true
          include_passed: true
          summary: true
